---
- name: Check 'samba_volumes_path' parameter
  assert:
    that:
      - "samba_volumes_path is defined"
      - "samba_volumes_path | length > 0"
    fail_msg: "parameter 'samba_volumes_path' is missing"

- name: Check 'samba_config_volume' parameter
  assert:
    that:
      - "samba_config_volume is defined"
      - "samba_config_volume | length > 0"
    fail_msg: "parameter 'samba_config_volume' is missing"

- name: Check 'samba_data_volume' parameter
  assert:
    that:
      - "samba_data_volume is defined"
      - "samba_data_volume | length > 0"
    fail_msg: "parameter 'samba_data_volume' is missing"

- name: Check 'samba_storages_volume' parameter
  assert:
    that:
      - "samba_storages_volume is defined"
      - "samba_storages_volume | length > 0"
    fail_msg: "parameter 'samba_storages_volume' is missing"

- name: Check 'samba_homes_volume' parameter
  assert:
    that:
      - "samba_homes_volume is defined"
      - "samba_homes_volume | length > 0"
    fail_msg: "parameter 'samba_homes_volume' is missing"
