---
- name: Create dockerimage directory
  file:
    path: "{{ samba_dockerfile_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy add-user script
  copy:
    src: files/add-samba-user.sh
    dest: "{{ samba_dockerfile_path }}/add-samba-user.sh"
    owner: root
    group: root
    mode: 0755
  register: docker_add_user_script

- name: Copy update-password script
  copy:
    src: files/update-samba-user-password.sh
    dest: "{{ samba_dockerfile_path }}/update-samba-user-password.sh"
    owner: root
    group: root
    mode: 0755
  register: docker_update_password_script

- name: Create supervisor config
  template:
    src: supervisord.conf.j2
    dest: "{{ samba_dockerfile_path }}/supervisord.conf"
    owner: root
    group: root
    mode: 0644
  register: docker_supervisor_config

- name: Template dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ samba_dockerfile_path }}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  register: dockerfile
