---
- name: create config directory
  file:
    path: "{{config_volume}}"
    state: directory
    owner: "{{samba_user}}"
    group: "{{samba_user}}"
    mode: 0755
  when: not(
    (config_volume is undefined)
    or
    (config_volume is none)
    or
    (config_volume | trim == '')
    )

- name: Create config directory structure
  file:
    path: "{{config_volume}}/etc"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not(
    (config_volume is undefined)
    or
    (config_volume is none)
    or
    (config_volume | trim == '')
    )

- name: Create etc/samba directory
  file:
    path: "{{config_volume}}/etc/samba"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not(
    (config_volume is undefined)
    or
    (config_volume is none)
    or
    (config_volume | trim == '')
    )

- name: create data directory
  file:
    path: "{{data_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: not(
    (data_volume is undefined)
    or
    (data_volume is none)
    or
    (data_volume | trim == '')
    )

# otherwise, samba will not start and crash with an error
- name: create data/private directory
  file:
    path: "{{data_volume}}/private"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: not(
    (data_volume is undefined)
    or
    (data_volume is none)
    or
    (data_volume | trim == '')
    )

- include: create-storage-volumes.yml

- name: create homes volume
  file:
    path: "{{homes_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: homes_volume is defined
    and homes_volume | length > 0
