---

- name: Create storage directory
  file:
    path: "{{ samba_storages_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Select storages with host path
  set_fact:
    storages_with_host_path: "{{
      samba_storages
      | selectattr('host_path', 'defined')
      | list
      }}"

- name: Create storage host directories
  file:
    path: "{{ item.host_path }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ storages_with_host_path }}"

- name: Select storages without host path
  set_fact:
    storages_without_host_path: "{{
      samba_storages
      | selectattr('host_path', 'undefined')
      | list
      }}"

- name: Create storage directories
  file:
    path: "{{ samba_storages_volume }}{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ storages_without_host_path }}"
