---
- include_tasks: check-parameters.yml
- include_tasks: create-docker-image.yml
- include_tasks: create-volumes.yml
- include_tasks: initialize-config.yml

- name: Create systemd unit file
  template:
    src: samba.systemd.j2
    dest: "/etc/systemd/system/{{ samba_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart samba service

- include_tasks: create-samba-users.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable service
  service:
    name: "{{ samba_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- include_tasks: update-password.yml
  with_items: "{{
   samba_users
   | selectattr('update_password', 'true')
   | list
   }}"
