---
- include: check-parameters.yml
- include: create-docker-image.yml
- include: create-volumes.yml
- include: initialize-config.yml

- name: Create systemd unit file
  template:
    src: samba.systemd.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart samba service

- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: true
  register: service_state
  changed_when: service_state.status.SubState != 'running'
  notify: Start samba service
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- include: create-samba-users.yml

- include: update-password.yml
  with_items: "{{
   users
   | selectattr('update_password', 'true')
   | list
   }}"

- name: Start systemd-managed docker containers
  meta: flush_handlers
