---
- include: create-docker-image.yml
- include: create_volumes.yml

- name: Create samba config file
  template:
    src: smb.conf.j2
    dest: "{{config_volume}}/smb.conf"
    owner: "{{samba_user}}"
    group: "{{samba_user}}"
    mode: 0644
  when: not(
    (config_volume is undefined)
    or
    (config_volume is none)
    or
    (config_volume | trim == '')
    )
  register: samba_config

- name: Create systemd unit file
  template:
    src: samba.systemd.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_service.changed

- name: Restart service
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: >
    dockerimage.changed
    or systemd_service.changed
    or samba_config.changed

- name: Start service (if not started already)
  service:
    name: "{{service_name}}"
    state: started

- include: create-samba-users.yml
