---
- name: copy dockerfile and image files
  copy:
    src: ./docker/
    dest: "{{dockerfile_path}}"
    owner: root
    group: root
    mode: preserve
  register: dockerfile_and_files

- name: build image
  docker_image:
    path: "{{dockerfile_path}}"
    name: "{{image_name}}:{{image_version}}"
    force: yes
  register: dockerimage
  when: dockerfile_and_files.changed

- include: create_volumes.yml

- name: Create samba config file
  template:
    src: smb.conf.j2
    dest: "{{config_volume}}/smb.conf"
    owner: root
    group: root
    mode: 0640
  when: not(
            (config_volume is undefined)
            or
            (config_volume is none)
            or
            (config_volume | trim == '')
          )
  register: samba_config

- name: Create systemd unit file
  template: src=samba.systemd.j2 dest=/etc/systemd/system/samba.service owner=root group=root mode=0550
  register: systemd_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_service.changed

- name: Restart service
  service: name=teamspeak state=restarted enabled=yes
  when: dockerimage.changed or systemd_service.changed or samba_config.changed
