---
- name: Update samba user password
  shell: |
    /usr/bin/docker exec {{container_name}} /update-samba-user-password.sh "{{item.username}}" '{{item.password}}'
  register: update_password
  changed_when: update_password.stdout | length > 0
