---
- name: Restart samba service
  systemd:
    name: "{{ samba_service_name }}"
    state: restarted
    daemon_reload: true
  register: samba_service_restart
  when: not (
    samba_service_start is defined
    and samba_service_start.changed
    )
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

# We can create samba users only if the container is already running
- name: Create samba user
  shell: |
    /usr/bin/docker exec {{ samba_container_name }} \
    /add-samba-user.sh "{{ item.username }}" \
                       '{{ item.password }}' \
                       "{{ item.uid }}"
  register: created_user
  changed_when: created_user.stdout | length > 0
  with_items: "{{ users_for_creation }}"
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
