---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-samba-xenial
    box: ubuntu/xenial64

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
  inventory:
    host_vars:
      ansible-samba-buster:
        ansible_python_interpreter: /usr/bin/python3
      ansible-samba-stretch:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
