---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template Dockerfile
      stat:
        path: /opt/samba/docker/Dockerfile
        checksum_algorithm: sha256
      register: docker_file
      # Expecting file to have content:
      #  (see expected.Dockerfile)
      failed_when: not (
        docker_file.stat.exists
        and docker_file.stat.checksum
        == 'f49d62eb06c27e29275244d4e80ba791f341c0e7ed1b7dcdec7023293227e267'
        )

    - name: Should create config directory
      stat:
        path: /srv/samba/config
      register: config_directory
      failed_when: not config_directory.stat.exists

    - name: Should create data directory
      stat:
        path: /srv/samba/data
      register: data_directory
      failed_when: not data_directory.stat.exists

    - name: Should create storage share directory
      stat:
        path: /srv/samba/storage_share
      register: storage_share_directory
      failed_when: not storage_share_directory.stat.exists

    - name: Should create storage out directory
      stat:
        path: /srv/samba/storages/out
      register: out_share_directory
      failed_when: not out_share_directory.stat.exists

  post_tasks:
    - name: Delete docker image
      docker_image:
        name: samba:4.11
        state: absent
      failed_when: false
