---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-samba
      alpine_version: '3.11'
      samba_version: '4.11'
      samba_port: 445
      interface: 0.0.0.0
      volumes_path: /srv/samba
      log_level: 2
      enable_homes: true
      enable_netbios: true
      netbios_name: mysamba
      unix_extensions: false
      users:
        - username: user1
          password: user$pwd
          uid: 2001
          update_password: false
        - username: user2
          password: user$pwd
          uid: 2002
          update_password: false
      storages:
        - name: Share
          path: /share
          host_path: /srv/samba/storage_share
          comment: Share storage
          browseable: true
          writable: true
          guest_access: true
        - name: Outgoing
          path: /out
          comment: Outgoing storage
          browseable: true
          writable: false
          guest_access: true
          write_list:
            - user1
        - name: Outgoing
          path: /out
          comment: Outgoing storage
          browseable: true
          writable: false
          guest_access: true
          write_list:
            - user1
