---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-samba
      samba_alpine_version: '3.11'
      samba_version: '4.11'
      samba_port: 445
      samba_interface: 0.0.0.0
      samba_volumes_path: /srv/samba
      samba_log_level: 2
      samba_enable_homes: true
      samba_enable_netbios: true
      samba_netbios_name: mysamba
      samba_unix_extensions: false
      samba_users:
        - username: user1
          password: user$pwd
          uid: 2001
          update_password: false
        - username: user2
          password: user$pwd
          uid: 2002
          update_password: false
      samba_storages:
        - name: Share
          path: /share
          host_path: /srv/samba/storage_share
          comment: Share storage
          browseable: true
          writable: true
          guest_access: true
        - name: Outgoing
          path: /out
          comment: Outgoing storage
          browseable: true
          writable: false
          guest_access: true
          write_list:
            - user1
        - name: Outgoing
          path: /out
          comment: Outgoing storage
          browseable: true
          writable: false
          guest_access: true
          write_list:
            - user1
