{% if alpine_version is not defined or alpine_version == 'latest' %}
FROM alpine
{% else %}
FROM alpine:{{alpine_version}}
{% endif %}

MAINTAINER borisskert <boris.skert@gmail.com>

{% if samba_version is defined and not samba_version == 'latest' %}
ENV SAMBA_VERSION={{samba_version}}
{% endif %}

RUN apk --no-cache --no-progress upgrade && \
    apk --no-cache --no-progress add \
        bash \
        supervisor \
{% if samba_version is not defined or samba_version == 'latest' %}
        samba \
        samba-common-tools
{% else %}
        samba=${SAMBA_VERSION} \
        samba-common-tools=${SAMBA_VERSION}
{% endif %}

COPY add-samba-user.sh /add-samba-user.sh
COPY update-samba-user-password.sh /update-samba-user-password.sh
COPY supervisord.conf /supervisord.conf

VOLUME ["/etc", "/var/lib/samba", "/var/log/samba", "/var/cache/samba", "/run/samba", "/storages", "/home"]

EXPOSE 135/tcp 137/udp 138/udp 139/tcp 445/tcp

ENTRYPOINT ["supervisord", "-c", "/supervisord.conf"]
